version: '3.2'

services:
  app:
    image: text_service
    command: gunicorn -b 0.0.0.0:8000 text_service.wsgi:application
    volumes:
      - .:/opt/app

  nginx:
    image: text_service_nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - app
